### ISSUE TITLE
Added support for new ASUS Wifi device

### ISSUE THREAD

**Issue by francoism90** [ulli-kroll/rtl8814au#13]
```
$ lsusb
Bus 001 Device 004: ID 0b05:1853 ASUSTek Computer, Inc.
```

Thanks!

**Comment by ssube** [comment]
I also have an ASUS AC-68 adapter with the `0b05:1853` product ID. Based on [the discussion here](https://github.com/diederikdehaas/rtl8814AU/pull/12), both `1852` and `1853` seem to be IDs for this chipset. I've been running [a forked driver](https://github.com/nazar-pc/RTL8814AU) for DKMS support and was pointed this way after [opening a PR](https://github.com/nazar-pc/RTL8814AU/pull/1) with the new IDs.
